# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 11:39
from __future__ import unicode_literals

import allauth.socialaccount.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'First Name')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('invite_id', models.CharField(max_length=20, null=True)),
                ('bookedcabs', models.ManyToManyField(blank=True, default=b'', to='cab.BookCab')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('invites', models.ManyToManyField(null=True, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('postedcabs', models.ManyToManyField(blank=True, default=b'', to='cab.PostCab')),
                ('user', models.OneToOneField(null=True, on_delete=allauth.socialaccount.models.SocialAccount, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
