# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 02:14
from __future__ import unicode_literals

import allauth.socialaccount.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'First Name')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('email_token', models.CharField(blank=True, max_length=32, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=allauth.socialaccount.models.SocialAccount, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
