# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 11:21
from __future__ import unicode_literals

import allauth.socialaccount.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'First Name')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('invite_id', models.CharField(max_length=20, null=True)),
                ('app_downloaded', models.BooleanField(default=False)),
                ('cabme_cash', models.BigIntegerField(default=0)),
                ('refer_stage', models.CharField(choices=[(b'0', b'nothing'), (b'1', b'application downloaded'), (b'2', b'invited 5'), (b'3', b'invited 25'), (b'4', b'invited 65'), (b'5', b'invited 125')], default=b'0', max_length=30)),
                ('bookedcabs', models.ManyToManyField(blank=True, default=b'', to='cab.BookCab')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('invites', models.ManyToManyField(null=True, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('postedcabs', models.ManyToManyField(blank=True, default=b'', to='cab.PostCab')),
                ('user', models.OneToOneField(null=True, on_delete=allauth.socialaccount.models.SocialAccount, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
