# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cabme_cash',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refer_stage',
            field=models.CharField(choices=[(b'0', b'nothing'), (b'1', b'application downloaded'), (b'2', b'invited 5'), (b'3', b'invited 25'), (b'4', b'invited 65'), (b'5', b'invited 125')], default=b'0', max_length=30),
        ),
    ]
