# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fbid',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
