# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
    ]
