# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_auto_20160903_2104'),
        ('registration', '0002_auto_20160903_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookedcabs',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='cab.BookCab'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postedcabs',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='cab.PostCab'),
        ),
    ]
