# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_auto_20160903_2104'),
        ('registration', '0003_auto_20160903_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bookedcabs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookedcabs',
            field=models.ManyToManyField(blank=True, default=b'', to='cab.BookCab'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postedcabs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postedcabs',
            field=models.ManyToManyField(blank=True, default=b'', to='cab.PostCab'),
        ),
    ]
