# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 15:33
from __future__ import unicode_literals

import allauth.socialaccount.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170107_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=allauth.socialaccount.models.SocialAccount, to=settings.AUTH_USER_MODEL),
        ),
    ]
