# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170118_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
