# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20161017_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
