# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'sedan', b'sedan'), (b'hatchback', b'hatchback'), (b'suv', b'suv')], max_length=10)),
                ('ac', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uniqueID', models.CharField(max_length=20)),
                ('price_sedan_ac', models.IntegerField(default=0)),
                ('price_sedan_nac', models.IntegerField(default=0)),
                ('price_hatch_ac', models.IntegerField(default=0)),
                ('price_hatch_nac', models.IntegerField(default=0)),
                ('price_suv_ac', models.IntegerField(default=0)),
                ('price_suv_nac', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='b_cab.Company')),
            ],
        ),
    ]
