# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_cab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabtype',
            name='name',
            field=models.CharField(choices=[(b'sedan', b'sedan'), (b'hatchback', b'hatchback'), (b'suv', b'suv')], max_length=10),
        ),
    ]
