# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('To', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('Date', models.CharField(max_length=10)),
                ('Date_return', models.CharField(default=b'', max_length=10)),
                ('Time', models.CharField(max_length=10)),
                ('Oneway', models.BooleanField(default=True)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
                ('Sharing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('To', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('DriverName', models.CharField(default=b'', max_length=100)),
                ('Date', models.CharField(max_length=10)),
                ('Date_return', models.CharField(default=b'', max_length=10)),
                ('Time', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=20)),
                ('cab_id', models.CharField(default=b'', max_length=1000)),
                ('price', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('To', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('Date', models.CharField(max_length=10)),
                ('Date_return', models.CharField(default=b'', max_length=10)),
                ('Time', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=20)),
                ('Smoking', models.BooleanField(default=False)),
                ('Pet', models.BooleanField(default=False)),
                ('Music', models.BooleanField(default=False)),
                ('SeatsAvail', models.IntegerField(default=2)),
                ('price', models.IntegerField(default=0)),
                ('cab_id', models.CharField(default=b'', max_length=1000)),
                ('user', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
