# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('To', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=10)),
                ('Oneway', models.BooleanField(default=True)),
                ('Price', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
                ('Sharing', models.BooleanField(default=False)),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PostCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('To', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=20)),
                ('Smoking', models.BooleanField(default=False)),
                ('Pet', models.BooleanField(default=False)),
                ('Music', models.BooleanField(default=False)),
                ('SeatsAvail', models.IntegerField(default=2)),
            ],
        ),
    ]
