# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cab', '0002_auto_20160903_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('To', models.CharField(choices=[(b'test', b'test')], max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=20)),
                ('Smoking', models.BooleanField(default=False)),
                ('Pet', models.BooleanField(default=False)),
                ('Music', models.BooleanField(default=False)),
                ('SeatsAvail', models.IntegerField(default=2)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cab',
            name='Music',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='Pet',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='SeatsAvail',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='Smoking',
        ),
        migrations.AddField(
            model_name='cab',
            name='DriverName',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.RemoveField(
            model_name='bookcab',
            name='Cust',
        ),
        migrations.AddField(
            model_name='bookcab',
            name='Cust',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
