# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cab', '0003_auto_20160903_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcab',
            name='user',
        ),
        migrations.AddField(
            model_name='postcab',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
