# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0003_auto_20170118_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='Date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='Date_return',
            field=models.CharField(blank=True, default=b'', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='From',
            field=models.CharField(blank=True, choices=[(b'test', b'test')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='Time',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cab',
            name='To',
            field=models.CharField(blank=True, choices=[(b'test', b'test')], max_length=100, null=True),
        ),
    ]
