# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_auto_20160903_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='cab_id',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='postcab',
            name='cab_id',
            field=models.CharField(default=b'', max_length=1000),
        ),
        migrations.AddField(
            model_name='postcab',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
