# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0005_auto_20160904_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='price',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='bookcab',
            name='Cust',
            field=models.ManyToManyField(related_name='userprofile', to='registration.UserProfile'),
        ),
    ]
