# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0007_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcab',
            name='Date_return',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='cab',
            name='Date_return',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='postcab',
            name='Date_return',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookcab',
            name='Date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cab',
            name='Date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='postcab',
            name='Date',
            field=models.CharField(max_length=10),
        ),
    ]
